"""onboarding

Revision ID: 01f3fd6023de
Revises: 8594a58a62eb
Create Date: 2024-10-31 04:32:25.511470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f3fd6023de'
down_revision = '8594a58a62eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('kra_pin_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('bank_account_details', sa.String(length=255), nullable=False))

    with op.batch_alter_table('welcome_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('welcome_emails', schema=None) as batch_op:
        batch_op.drop_column('opened_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('bank_account_details')
        batch_op.drop_column('kra_pin_number')
        batch_op.drop_column('national_id_number')

    # ### end Alembic commands ###
