"""done

Revision ID: 988753bfa62d
Revises: 3cc8d0d93ebc
Create Date: 2024-11-01 05:23:22.575350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988753bfa62d'
down_revision = '3cc8d0d93ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('kra_pin_number', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['kra_pin_number'])
        batch_op.create_unique_constraint(None, ['national_id_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('kra_pin_number')
        batch_op.drop_column('national_id_number')

    # ### end Alembic commands ###
