"""done

Revision ID: db0db8b9108a
Revises: 461bc2c0df38
Create Date: 2024-11-02 02:28:39.076544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db0db8b9108a'
down_revision = '461bc2c0df38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheets')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('break_end_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('clock_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('clock_in_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('break_end_time')
        batch_op.drop_column('break_start_time')

    op.create_table('timesheets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='timesheets_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='timesheets_pkey')
    )
    # ### end Alembic commands ###
