"""done

Revision ID: fc73d87e935f
Revises: 01f3fd6023de
Create Date: 2024-10-31 04:42:36.170504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc73d87e935f'
down_revision = '01f3fd6023de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('branch_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=False))
        batch_op.drop_column('bank_account_details')
        batch_op.drop_column('kra_pin_number')
        batch_op.drop_column('national_id_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kra_pin_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_account_details', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_name')
        batch_op.drop_column('branch_name')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
